/*
 * executor.c
 * 
 * The executor is the core of the shell. It takes the AST (Pipeline structure)
 * generated by the parser and translates it into actual running processes.
 * It manages the lifecycle of process creation (fork), image replacement (execve),
 * and inter-process communication (pipes and redirection via dup2).
 */

#include "executor.h"
#include "builtins.h"
#include "syscalls.h"
#include "string_utils.h"
#include "memory.h"
#include "jobs.h"
#include "env.h"
#include "signals.h"
#include "terminal.h"

// Constants for open() syscall
#define O_RDONLY 00     // Open for reading only
#define O_WRONLY 01     // Open for writing only
#define O_CREAT  0100   // Create file if it does not exist
#define O_TRUNC  01000  // Truncate file to zero length if it exists
#define O_APPEND 02000  // Append to the file (writes always append)

/*
 * Resolves a command name (e.g. "ls") to a full absolute path (e.g. "/bin/ls").
 * If the command already contains a slash, it's treated as a direct path.
 * Otherwise, it splits the PATH environment variable by ':' and checks each directory.
 */
static char *find_executable(const char *cmd) {
    if (!cmd) return NULL;
    
    // If command contains '/', do not search PATH
    for (int i = 0; cmd[i]; i++) {
        if (cmd[i] == '/') return (char *)cmd;
    }
    
    char *path = get_env_val("PATH");
    if (!path) return (char *)cmd; // Fallback to raw string if no PATH
    
    // We use a static buffer to build candidate paths. 
    // In a production shell, we would dynamically allocate this.
    static char full_path[1024];
    const char *p = path;
    
    while (*p) {
        const char *start = p;
        while (*p && *p != ':') p++;
        
        size_t dir_len = p - start;
        if (dir_len + 1 + str_len(cmd) < sizeof(full_path)) {
            mem_cpy(full_path, start, dir_len);
            full_path[dir_len] = '/';
            str_cpy(full_path + dir_len + 1, cmd);
            
            // Check if the file exists by attempting to open it read-only
            // Typically, one would use sys_access(..., X_OK), but opening it 
            // is a minimalist alternative without adding another syscall wrapper.
            int fd = sys_open(full_path, O_RDONLY, 0);
            if (fd >= 0) {
                sys_close(fd);
                return full_path;
            }
        }
        if (*p == ':') p++;
    }
    return (char *)cmd; // Return original if not found
}

/*
 * Executes a pipeline of commands (e.g. "cat file.txt | grep error | wc -l > out.txt").
 */
int execute_pipeline(Pipeline *pipeline) {
    if (pipeline->num_commands == 0) return 0;
    
    // Special case: Single builtin command (e.g., "cd /tmp").
    if (pipeline->num_commands == 1 && is_builtin(pipeline->commands[0].argv[0])) {
        execute_builtin(&pipeline->commands[0]);
        return 0; // Return 0 for success (simplified)
    }
    
    // Arrays to track pipes and child Process IDs (PIDs)
    int pipes[MAX_COMMANDS - 1][2];
    pid_t pids[MAX_COMMANDS];
    pid_t pgid = 0;
    
    // Phase 1: Create all necessary pipes in the parent before forking.
    // A pipe is a unidirectional data channel in the kernel.
    for (int i = 0; i < pipeline->num_commands - 1; i++) {
        if (sys_pipe(pipes[i]) < 0) {
            print_str(2, "pipe failed\n");
            return -1;
        }
    }
    
    // Iterate through each command in the pipeline
    for (int i = 0; i < pipeline->num_commands; i++) {
        Command *cmd = &pipeline->commands[i];
        
        // Handle Here-Document (<<) in parent before forking
        int heredoc_pipe[2] = {-1, -1};
        if (cmd->heredoc_delimiter) {
            if (sys_pipe(heredoc_pipe) == 0) {
                char line[1024];
                while (1) {
                    int n = read_line_raw("> ", line, sizeof(line));
                    if (n == 0) {
                        print_str(1, "\n");
                        break;
                    }
                    if (str_cmp(line, cmd->heredoc_delimiter) == 0) {
                        break;
                    }
                    sys_write(heredoc_pipe[1], line, str_len(line));
                    sys_write(heredoc_pipe[1], "\n", 1);
                }
                sys_close(heredoc_pipe[1]); // Close write end so child gets EOF
            }
        }
        
        // sys_fork() clones the current process. It returns 0 to the newly created
        // child process, and returns the child's PID to the parent process.
        pid_t pid = sys_fork();
        
        if (pid == 0) {
            // === CHILD PROCESS START ===
            reset_signals(); // Child processes should respond to Ctrl+C / Ctrl+Z
            
            pid_t my_pid = sys_getpid();
            if (i == 0) pgid = my_pid;
            sys_setpgid(my_pid, pgid);
            
            if (!pipeline->background) {
                set_foreground_pgrp(0, pgid);
            }
            
            // 1. Wire up pipes using dup2.
            // dup2(oldfd, newfd) forcefully closes newfd if it's open, 
            // and then makes newfd a clone of oldfd.
            
            if (i > 0) {
                // If this is not the first command, its standard input (0) 
                // should come from the read end of the previous pipe.
                sys_dup2(pipes[i-1][0], 0);
            }
            if (i < pipeline->num_commands - 1) {
                // If this is not the last command, its standard output (1)
                // should go into the write end of the current pipe.
                sys_dup2(pipes[i][1], 1);
            }
            
            // 2. Close all pipe descriptors. 
            // The dup2 calls already copied the descriptors we need to stdin/stdout.
            // Keeping the original pipe ends open will cause programs (like 'cat' or 'grep')
            // to hang forever waiting for an EOF that will never arrive.
            for (int j = 0; j < pipeline->num_commands - 1; j++) {
                sys_close(pipes[j][0]);
                sys_close(pipes[j][1]);
            }
            
            // 3. Handle input redirection ('<') or Here-Doc ('<<')
            if (cmd->heredoc_delimiter && heredoc_pipe[0] != -1) {
                sys_dup2(heredoc_pipe[0], 0);
                sys_close(heredoc_pipe[0]);
            } else if (cmd->redirect_in) {
                int fd_in = sys_open(cmd->redirect_in, O_RDONLY, 0);
                if (fd_in < 0) {
                    print_str(2, "No such file or directory: ");
                    print_str(2, cmd->redirect_in);
                    print_str(2, "\n");
                    sys_exit(1);
                }
                sys_dup2(fd_in, 0);
                sys_close(fd_in);
            }
            
            if (cmd->redirect_out) {
                int flags = O_WRONLY | O_CREAT | (cmd->append_out ? O_APPEND : O_TRUNC);
                // 0644 means rw-r--r-- permissions for the created file
                int fd = sys_open(cmd->redirect_out, flags, 0644);
                if (fd < 0) {
                    print_str(2, "open output failed\n");
                    sys_exit(1);
                }
                sys_dup2(fd, 1); // Replace stdout with file
                sys_close(fd);
            }
            
            // 4. Handle stderr merging ('2>&1')
            if (cmd->merge_stderr) {
                sys_dup2(1, 2);
            }

            // 5. Execute the command
            if (is_builtin(cmd->argv[0])) {
                execute_builtin(cmd);
                sys_exit(0);
            } else {
                char *exec_path = find_executable(cmd->argv[0]);
                char **env_arr = get_env_array();
                // sys_execve replaces the memory image of this child process entirely
                // with the new binary (e.g. /bin/ls). If successful, it NEVER returns.
                sys_execve(exec_path, cmd->argv, env_arr);
                
                // If we reached here, execve failed (e.g. command not found, or bad permissions).
                print_str(2, "execve failed: ");
                print_str(2, cmd->argv[0]);
                print_str(2, "\n");
                sys_exit(1); // Exit child immediately
            }
            
            // === CHILD PROCESS END ===
        } else if (pid < 0) {
            print_str(2, "fork failed\n");
            return -1;
        } else if (pid > 0) {
            // === PARENT PROCESS ===
            pids[i] = pid; // Track child process ID
            if (i == 0) pgid = pid;
            sys_setpgid(pid, pgid);
            if (heredoc_pipe[0] != -1) sys_close(heredoc_pipe[0]);
        }
    }
    
    // Phase 3: Parent process must close all pipe ends.
    // If the parent leaves write ends open, the reader commands in the pipeline 
    // will block indefinitely waiting for the parent to write data.
    for (int i = 0; i < pipeline->num_commands - 1; i++) {
        sys_close(pipes[i][0]);
        sys_close(pipes[i][1]);
    }
    
    int final_status = 0;
    
    // Phase 4: Wait for children or detach them (background)
    if (!pipeline->background) {
        set_foreground_pgrp(0, pgid); // Hand over terminal
        
        int status;
        for (int i = 0; i < pipeline->num_commands; i++) {
            pid_t p = sys_wait4(pids[i], &status, WUNTRACED, NULL);
            if (i == pipeline->num_commands - 1) {
                // Extract exit status of the last command in pipeline
                final_status = (status >> 8) & 0xff;
            }
            if (p > 0 && WIFSTOPPED(status)) {
                add_job(pgid, pipeline->commands[0].argv[0], JOB_STOPPED);
                print_str(1, "\n[Stopped] "); print_str(1, pipeline->commands[0].argv[0]); print_str(1, "\n");
                final_status = 146; // SIGTSTP + 128
                break; 
            }
        }
        
        // Parent shell takes back the terminal
        set_foreground_pgrp(0, sys_getpgrp());
    } else {
        // Run in background: Add to job tracker
        int jid = add_job(pgid, pipeline->commands[0].argv[0], JOB_RUNNING);
        print_str(1, "["); print_int(1, jid); print_str(1, "] "); print_int(1, pgid); print_str(1, "\n");
        final_status = 0;
    }
    
    return final_status;
}

int execute_ast(ASTNode *node) {
    if (!node) return 0;
    
    if (node->type == NODE_PIPELINE) {
        return execute_pipeline(&node->data.pipeline);
    } else if (node->type == NODE_SEQUENCE) {
        execute_ast(node->data.binary.left);
        return execute_ast(node->data.binary.right);
    } else if (node->type == NODE_AND) {
        int status = execute_ast(node->data.binary.left);
        if (status == 0) {
            return execute_ast(node->data.binary.right);
        }
        return status;
    } else if (node->type == NODE_OR) {
        int status = execute_ast(node->data.binary.left);
        if (status != 0) {
            return execute_ast(node->data.binary.right);
        }
        return status;
    } else if (node->type == NODE_IF) {
        int status = execute_ast(node->data.if_stmt.condition);
        if (status == 0) {
            if (node->data.if_stmt.then_branch) {
                return execute_ast(node->data.if_stmt.then_branch);
            }
        } else {
            if (node->data.if_stmt.else_branch) {
                return execute_ast(node->data.if_stmt.else_branch);
            }
        }
        return 0;
    } else if (node->type == NODE_WHILE) {
        int last_status = 0;
        while (execute_ast(node->data.while_stmt.condition) == 0) {
            if (node->data.while_stmt.body) {
                last_status = execute_ast(node->data.while_stmt.body);
            }
        }
        return last_status;
    }
    return 0;
}

void execute_string(const char *str, int out_fd) {
    if (out_fd != -1 && out_fd != 1) {
        sys_dup2(out_fd, 1);
        sys_close(out_fd);
    }
    
    Token tokens[256];
    int token_count = tokenize(str, tokens, 256);
    if (token_count > 0) {
        ASTNode *ast = parse(tokens);
        if (ast) {
            execute_ast(ast);
        }
    }
}
